In [1]:
!pip install transformers==4.5.0 fugashi==1.1.0 ipadic==1.0.0

     |████████████████████████████████| 2.1 MB 7.5 MB/s 
     |████████████████████████████████| 486 kB 53.4 MB/s 
     |████████████████████████████████| 13.4 MB 29.1 MB/s 
     |████████████████████████████████| 895 kB 54.6 MB/s 
     |████████████████████████████████| 3.3 MB 49.2 MB/s 
  Created wheel for ipadic: filename=ipadic-1.0.0-py3-none-any.whl size=13556723 sha256=01b6653978b6b791a5c7348afd22848a2285f2ebe52549ff790befd754e2f6f7
  Stored in directory: /root/.cache/pip/wheels/33/8b/99/cf0d27191876637cd3639a560f93aa982d7855ce826c94348b
Successfully built ipadic


In [2]:
import torch
from transformers import BertJapaneseTokenizer, BertModel

In [27]:
ModelName = "cl-tohoku/bert-base-japanese-whole-word-masking"
bert_tokenizer = BertJapaneseTokenizer.from_pretrained(ModelName, from_tf=True)
bert_model = BertModel.from_pretrained(ModelName, from_tf=True)

All TF 2.0 model weights were used when initializing BertModel.

Some weights of BertModel were not initialized from the TF 2.0 model and are newly initialized: ['embeddings.position_ids']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [28]:
bert_model.config

BertConfig {
  "_name_or_path": "cl-tohoku/bert-base-japanese-whole-word-masking",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "tokenizer_class": "BertJapaneseTokenizer",
  "transformers_version": "4.5.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 32000
}

In [29]:
tmp = "韓国日本大使館幹部処分を首脳会談条件に"

In [30]:
encoding = bert_tokenizer(tmp, max_length=50, padding="max_length", truncation=True, return_tensors="tf")
encoding

{'input_ids': <tf.Tensor: shape=(1, 50), dtype=int32, numpy=
array([[    2,  1758,    91,  8911,  5444,  3751,    11, 11056,  8073,
         1977,     7,     3,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 50), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 50), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]], dtype=int32)>}

SyntaxError: ignored

In [31]:
output = bert_model(input_ids)

AttributeError: ignored

In [20]:
"".join(bert_tokenizer.convert_ids_to_tokens(encoding["input_ids"]))

TypeError: ignored